### ISSUE TITLE
Python 3.6 Version

### ISSUE THREAD

**Issue by john9631** [timbertson/piep#14]
Tim, 

I am currently testing a version for 3.6+.  It should also work for 3.5 but I'm not testing it. 

Issues at present include:
- removed version test as it struggled with Anaconda 
- sh uses **vargs for stdout but it's throwing errors so currently removed & sh now works
- 20% slower than 2.7 so cythonized line.py to give slight gain against 2.7 (make optional) 
- called piep3 and ignoring 2 compatibility. 

Would you like it back in a few weeks after more testing?

**Comment by timbertson** [comment]
Thanks, that sounds good 👍 . I haven't worked on piep in a long time though, so I may be slow to get back into it.

To be honest I don't think I'd bother with cython, as I'd expect the maintenance burden & build complexity to outweigh the performance improvements.

I'm not sure what Anaconda is, I'm assuming there's a way to fix the version test & `sh` issues but I can't really comment without seeing some code.

`piep3` is unfortunate, but probably the best choice. At some point I might want to make 3 the default (i.e. have both `piep2` & `piep3`, then eventually switch `piep` to `piep3`), but that's probably a long way off so `piep3` is the right choice - extra points if you want to make a `piep2` alias ;)

**Comment by john9631** [comment]
I've created a version of the branch that will install under python 2 or python 3. Just some hand tests this morning mainly on the 3 version. Cython excluded so the big file test runs 25% slower on 3 than 2.

Anaconda is one of the two big Python distributions which lets you install a complete environment without messing with your local Python.  I've tested the new version with my local python 2.7 and with 3.6 in the Anaconda package and it seems good so far.  The doc changes_for_3 explains most of the changes I've made but a diff on main.py is worthwhile :)

I've not used unit tests so I'm not sure how to use your tests.  Can you enlighten me or suggest a link?

**Comment by john9631** [comment]
I'm not sure why I'm getting an extra blank line running the sh command under Python 3.  Its easily removed but, as with the need to remove self.kwargs its indicative of a problem in my understanding (p2 is python2, p0 is one of my python3 versions).

https://i.imgur.com/Sj3UDlP.png

**Comment by timbertson** [comment]
Hmm, the diff is pretty massive - it looks like your editor may have converted whitespace (piep uses tabs) in every file you touched. Are you able to reverse that? With all those whitespace changes it's hard to see the meaningful changes. Also, there's no need to check in the `.idea` files since they're specific to your machine.

What error did you actually get when you passed along `**kwargs`? That shouldn't have changed in python3 as far as I know.

> I've not used unit tests so I'm not sure how to use your tests. Can you enlighten me or suggest a link?

Does `make test` work? It's using http://nose.readthedocs.io/en/latest/, but I haven't run the unit tests in a while either, so if you can't get it working then I can probably have a go once your branch is in an otherwise decent shape.

**Comment by john9631** [comment]
The error follows (the p1 version has this line).  Ill convert the spaces to tabs & recommit. 

self.proc = subprocess.Popen(self.cmd, **self.kwargs)

___

~ > ls | p0 'os.path.isfile(p) | sh("wc", "-l", p)'                                                                             1 start_time

1 stop_time
50000 testmedium.txt
4 testshort.txt
32 ttt.py

~ > ls | p1 'os.path.isfile(p) | sh("wc", "-l", p)'                                                                             
a bytes-like object is required, not 'str'

**Comment by timbertson** [comment]
Thanks @john9631 , I'll have a look at at your branch and see if I can get the tests all working 👍.

After reconsidering for a few days, I'm tempted to just switch over to python 3 support rather than spend too much effort maintaining dual code paths - the current version of piep has been stable for a long time, so anyone who really needs python2 would just have to stick to that version.

**Comment by timbertson** [comment]
For the record, the sh() error became a bit more obvious with `--debug`:

```
Traceback (most recent call last):
  File "/home/tim/dev/python/piep/piep/main.py", line 27, in main
    print_results(lines, opts)
  File "/home/tim/dev/python/piep/piep/main.py", line 77, in print_results
    print_line(line)
  File "/home/tim/dev/python/piep/piep/shell.py", line 48, in __str__
    return (self.stdout or '').rstrip('\n\r')
TypeError: a bytes-like object is required, not 'str'
a bytes-like object is required, not 'str'
```

i.e. it just needed to decode the `stdout` bytes before it could `strip` them. Your change ended up up not accumulating any `stdout` bytes, so it fell back to `''` instead.

I've squashed your commits, taken out the accidental whitespace changes and got all the tests passing, in 93c3256c9b3c061109f831f391de7a7913211b58 . I had to hand pick some of the changes so let me know if you think I may have missed something - but all the tests pass in python3 now, so that's a good sign. Thanks again for your help :)
